CC = cc68x

tst_obj.tos: tst_obj.o model.o bitmap.o
	$(CC) -g tst_obj.o model.o bitmap.o -o tst_obj.tos

tst_obj.o: tst_obj.c model.h types.h bitmap.h
	$(CC) -c tst_obj.c

bitmap.o: bitmap.c bitmap.h
	$(CC) -c bitmap.c

model.o: model.c model.h types.h
	$(CC) -c model.c